version: "3.9"

# LOCAL DEV

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: tail -f /dev/null
    env_file: .env
    volumes:
      - type: bind
        source: ./
        target: /app/
    depends_on:
      - mongodb

  mongodb:
    ports:
      - 27017:27017
    container_name: mongobongo
    env_file: .env
    image: mongo:5.0.1